name: WordPress PHPCS Check

on:
  push:
    branches: [main]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Allow plugin
        run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install dependencies
        run: composer require --dev squizlabs/php_codesniffer wp-coding-standards/wpcs

      - name: Show installed coding standards
        run: vendor/bin/phpcs -i

      - name: Run PHPCS (WordPress coding standard)
        run: vendor/bin/phpcs --standard=WordPress --ignore=/vendor --extensions=php .
